BEGIN
 
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Z_PJPUPPSR_COMP]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[Z_PJPUPPSR_COMP]
END
 
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Z_PJPUPPSR_OC]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[Z_PJPUPPSR_OC]
END
 
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Z_PJPUPPSR_PROJ]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[Z_PJPUPPSR_PROJ]
END
 
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Z_PJPUPPSR_RND]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[Z_PJPUPPSR_RND]
END
 
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Z_PJPUPPSR_TEST_10]') AND type in (N'U'))
BEGIN
	DROP TABLE [dbo].[Z_PJPUPPSR_TEST_10]
END
 
INSERT INTO DB_TABLE_VERS ( TABLE_NAME, CUR_VERS_ID, CONV_DT, COMMENTS, CONV_CP_VERS_ID, MODIFIED_BY, TIME_STAMP, ROWVERSION ) 
VALUES ( 'dbc_820_11694', '8.2.0', GETDATE(), 'dbc_820_11694 has been applied.', ' ', 'DELTEK', GETDATE(), 0 );
 
COMMIT;
 
END