BEGIN
 
IF CheckObject('DEFAULT','TABLE','Z_PJPUPPSR_COMP') = '1' THEN
	EXECUTE IMMEDIATE 'DROP TABLE Z_PJPUPPSR_COMP CASCADE CONSTRAINTS';
END IF;
 
IF CheckObject('DEFAULT','TABLE','Z_PJPUPPSR_OC') = '1' THEN
	EXECUTE IMMEDIATE 'DROP TABLE Z_PJPUPPSR_OC CASCADE CONSTRAINTS';
END IF;
 
IF CheckObject('DEFAULT','TABLE','Z_PJPUPPSR_PROJ') = '1' THEN
	EXECUTE IMMEDIATE 'DROP TABLE Z_PJPUPPSR_PROJ CASCADE CONSTRAINTS';
END IF;
 
IF CheckObject('DEFAULT','TABLE','Z_PJPUPPSR_RND') = '1' THEN
	EXECUTE IMMEDIATE 'DROP TABLE Z_PJPUPPSR_RND CASCADE CONSTRAINTS';
END IF;
 
IF CheckObject('DEFAULT','TABLE','Z_PJPUPPSR_TEST_10') = '1' THEN
	EXECUTE IMMEDIATE 'DROP TABLE Z_PJPUPPSR_TEST_10 CASCADE CONSTRAINTS';
END IF;
 
INSERT INTO DB_TABLE_VERS ( TABLE_NAME, CUR_VERS_ID, CONV_DT, COMMENTS, CONV_CP_VERS_ID, MODIFIED_BY, TIME_STAMP, ROWVERSION ) 
VALUES ( 'dbc_820_11694', '8.2.0', SYSDATE, 'dbc_820_11694 has been applied.', ' ', 'DELTEK', SYSDATE, 0 );
 
COMMIT;
 
END;
 
