name: Oracle to SQL Conversion

on:
  push:
    paths:
      - 'scripts/oracle/**'
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install anthropic

    - name: Convert Oracle scripts
      env:
        CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      run: |
        for file in scripts/oracle/*.sql; do
          if [ -f "$file" ]; then
            filename=$(basename "$file")
            python convert.py "$file" "scripts/sql/$filename"
          fi
        done

    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add scripts/sql/
        git commit -m "Convert Oracle scripts to SQL Server" || echo "No changes to commit"
        git push
